// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPiou5Z2YTp8Kh8fF0-daTFwM_2bcKkqg',
    appId: '1:199047516422:web:7821a117d01122a9200e87',
    messagingSenderId: '199047516422',
    projectId: 'ziya-project',
    authDomain: 'ziya-project.firebaseapp.com',
    storageBucket: 'ziya-project.firebasestorage.app',
    measurementId: 'G-0TE94134L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCXU47NycE1FlCtV3Nk74jPtWPzZoB_8g',
    appId: '1:199047516422:android:f8095942cc72534b200e87',
    messagingSenderId: '199047516422',
    projectId: 'ziya-project',
    storageBucket: 'ziya-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPiou5Z2YTp8Kh8fF0-daTFwM_2bcKkqg',
    appId: '1:199047516422:web:c2305bd125ba9405200e87',
    messagingSenderId: '199047516422',
    projectId: 'ziya-project',
    authDomain: 'ziya-project.firebaseapp.com',
    storageBucket: 'ziya-project.firebasestorage.app',
    measurementId: 'G-WVE858LXQM',
  );
}
